services:
  hawki_rag_app:
    build:
      args:
        - DOCKER_PROJECT_HOST=localhost:8080
        - DOCKER_PROJECT_PATH=/
        - DOCKER_PROJECT_PROTOCOL=http
    ports:
      - "127.0.0.1:8080:80"
    networks: !override
      - default
