[project]
name = "hawki-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yazdan Asadi", email = "wentlerhiphop@gmail.com" }
]
requires-python = "==3.11.15"
dependencies = [
    "raganything>=0.0.1",
]

[project.scripts]
hawki-bridge = "hawki_bridge:main"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"


[project.optional-dependencies]
cpu = [
  "torch==2.13.0",
]
cu130 = [
  "torch==2.13.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu130" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu130", extra = "cu130" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.workspace]
members = []
