[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.log

[program:laravel-server]
command=php artisan serve --host=0.0.0.0 --port=8002
directory=/var/www
user=www-data
autostart=true
autorestart=true
stdout_logfile=/var/log/laravel-server.log
stderr_logfile=/var/log/laravel-server.log

#[program:queue-worker]
#command=php artisan queue:work --queue=default --tries=3 --timeout=3600 --sleep=3 --max-jobs=1000
#directory=/var/www
#user=www-data
#autostart=true
#autorestart=true
#redirect_stderr=true
#stdout_logfile=/var/log/queue-worker.log
#stderr_logfile=/var/log/queue-worker.log
#stopwaitsecs=3600

#[program:rabbitmq-listener]
#command=php artisan communication:listen --service=rabbitmq --channels=scrape-events
#directory=/var/www
#user=www-data
#autostart=true
#autorestart=true
#redirect_stderr=true
#stdout_logfile=/var/log/rabbitmq-listener.log
#stderr_logfile=/var/log/rabbitmq-listener.log
#stopwaitsecs=10
